WATCHLIST = {
    "Pharma": [
        "Sun Pharmaceutical Industries",
        "Dr. Reddy's Laboratories",
        "Cipla",
        "Lupin",
        "Aurobindo Pharma",
        "Divis Laboratories",
        "Cadila Healthcare",
        "Torrent Pharmaceuticals",
        "Biocon",
        "Glenmark Pharmaceuticals",
        "Alkem Laboratories",
        "Ipca Laboratories",
        "Mankind Pharma",
        "Syngene International",
        "Piramal Pharma",
        "Granules India",
        "Laurus Labs",
        "Ajanta Pharma",
        "Hetero Labs",
        "Strides Pharma Science",
        "Natco Pharma",
        "Jubilant Pharmova",
        "Sanofi India",
        "Abbott India",
        "Pfizer India",
        "Novartis India",
        "GSK Pharmaceuticals",
        "Neuland Laboratories",
        "Shilpa Medicare",
        "Eris Lifesciences",
    ],
    "FMCG": [
        "Hindustan Unilever",
        "ITC",
        "Nestle India",
        "Britannia Industries",
        "Marico",
        "Dabur India",
        "Godrej Consumer Products",
        "Colgate-Palmolive India",
        "Asian Paints",
        "Tata Consumer Products",
        "Adani Wilmar",
        "Parle Agro",
        "MTR Foods",
        "Kellogg India",
        "Pepsico India",
        "Coca-Cola India",
        "Emami",
        "Procter & Gamble India",
        "Bajaj Consumer Care",
        "Haldiram's",
        "Amul",
        "Milkfood",
        "Heritage Foods",
        "Vadilal Industries",
        "Zydus Wellness",
        "GlaxoSmithKline Consumer Healthcare",
        "Nirma",
        "Jyothy Labs",
        "Patanjali Ayurved",
        "Ruchi Soya Industries",
    ],
    "Manufacturing": [
        "Tata Motors",
        "Mahindra & Mahindra",
        "Maruti Suzuki India",
        "Ashok Leyland",
        "Bajaj Auto",
        "Larsen & Toubro",
        "Reliance Industries",
        "Adani Enterprises",
        "Tata Steel",
        "JSW Steel",
        "Hindalco Industries",
        "Bharat Heavy Electricals",
        "Siemens India",
        "ABB India",
        "Cummins India",
        "Thermax",
        "Kirloskar Brothers",
        "Bharat Forge",
        "Escorts Kubota",
        "Voltas",
        "Blue Star",
        "Godrej & Boyce",
        "Amara Raja Batteries",
        "Exide Industries",
        "Supreme Industries",
        "Astral Poly Technik",
        "Finolex Industries",
        "Jindal Steel & Power",
        "Coal India",
        "Hindustan Zinc",
    ],
    "Services": [
        "Tata Consultancy Services",
        "Infosys",
        "Wipro",
        "HCL Technologies",
        "Tech Mahindra",
        "Reliance Jio",
        "Bharti Airtel",
        "Vodafone Idea",
        "State Bank of India",
        "HDFC Bank",
        "ICICI Bank",
        "Axis Bank",
        "Kotak Mahindra Bank",
        "Bajaj Finance",
        "Adani Ports & SEZ",
        "InterGlobe Aviation",
        "SpiceJet",
        "MakeMyTrip",
        "Info Edge India",
        "Zomato",
        "Policybazaar",
        "Nykaa",
        "Delhivery",
        "PB Fintech",
        "One 97 Communications",
        "Indian Hotels Company",
        "Lemon Tree Hotels",
        "GMR Infrastructure",
        "Apollo Hospitals",
        "Max Healthcare",
    ],
}

EXCLUDED_COMPANIES = [
    "delhivery",
    "blue dart",
    "dtdc",
    "fedex",
    "dhl",
    "ups",
    "ecom express",
    "xpressbees",
    "shadowfax",
    "uber",
    "ola",
    "rapido",
    "zomato",
    "swiggy",
    "amazon logistics",
    "flipkart logistics",
    "ekart logistics",
    "india post",
    "tci express",
    "gati",
    "safexpress",
    "vtrans",
    "trackon courier",
    "professional couriers",
    "om Logistics",
    "st courier",
]
